#!/usr/bin/env python3
# vi: set shiftwidth=4 tabstop=8 expandtab:
#
# Nombre: Nestor Eduardo Hernandez Uribe
# No. Control: 18011339
# Calificación: XXX

def fibonacci(N):
    if(N == 0):
        return 0
    elif (N == 1):
        return 1
    else:
        return fibonacci(N -1) + fibonacci(N -2)

def main():
    numero = eval(input("Escribe un número: "))
    print("La posición", numero, "de fibonacci es", fibonacci(numero))


if __name__ == "__main__":
    main()
