#!/usr/bin/env python3
# vi: set shiftwidth=4 tabstop=8 expandtab:
#
# Nombre: Samuel Rodriguez Garcia 
# No. Control: 1901135
# Calificación: XXX

def Fibonacci(Numero):
    if(Numero==0):
        return 0
    elif(Numero==1):
        return 1
    else:
        return (Fibonacci(Numero-2)+Fibonacci(Numero-1)) 
n=int(input("Ingrese el valor: "))
print("Serie:")
for n in range(0, n):
  print(Fibonacci(n))


