#!/usr/bin/env python3
# vi: set shiftwidth=4 tabstop=8 expandtab:
#
# Nombre: Lopez Peter Ubaldo
# No. Control: 19012245
# Calificación: XXX

x = 0
y = 1
z = 0

while True:
    n = eval(input("Escribe un número: "))   
    if n>1:
         break
        
for i in range(0,n):
    print(f"{z}", end="")
    x=y
    y=z
    z=x+y
    print("")
