#!/usr/bin/env python3
# vi: set shiftwidth=4 tabstop=8 expandtab:
#
# Nombre: Fuentes Soto Alan Alexander
# No. Control: 19011308
# Calificación: XXX

def OrdenamientoSeleccion(Numbers):
    for i in range(len(Numbers)):
        min=i;
        for j in range(i,len(Numbers)):
            if(Numbers[j] < Numbers[min]):
                min=j;
        if(min != i):
            aux=Numbers[i];
            Numbers[i]=Numbers[min];
            Numbers[min]=aux;
    print (Numbers);
 
Numbers=[6,5,3,1,8,7,2,4];
OrdenamientoSeleccion(Numbers);
